const ourFilms = [{
        id: "1",
        title: "The Conjuring",
        poster: "https://m.media-amazon.com/images/I/81yAfVk+7UL._AC_SY606_.jpg",
        decription: "Paranormal investigators Ed and Lorraine Warren work to help a family .",
        rate: 5,
        type: "Horror",
    },
    {
        id: "2",
        title: "The Grudge",
        poster: "https://aws-cf.imdoc.fr/prod/photos/8/6/1/11904861/29176577/big-29176577abb.jpg?v=2",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 5,
        type: "Horror",
    },
    {
        id: "3",
        title: "The Ring",
        poster: "https://m.media-amazon.com/images/I/41CGtdWTDvL._AC_.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 1,
        type: "Action",
    },
    {
        id: "4",
        title: "The Shawshank Redemption",
        poster: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
        type: "Romance",
    },
    {
        id: "5",
        title: "The Godfather",
        poster: "https://ih1.redbubble.net/image.1275475865.6561/pp,504x498-pad,600x600,f8f8f8.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
        type: "Comedies",
    },
    {
        id: "6",
        title: "The Godfather: Part II",
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0hYUlSTUgCxfY-8ACz_E3CQWDKShEYEvGFw&usqp=CAU",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
        type: "Action",
    },
    {
        id: "7",
        title: "The Dark Knight",
        poster: "https://m.media-amazon.com/images/I/51CbCQNMyiL._AC_.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 2,
        type: "Comedies",
    },
    {
        id: "8",
        title: "12 Angry Men",
        poster: "https://m.media-amazon.com/images/I/81zZhjymV7L._AC_SL1500_.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 4,
        type: "Action",
    },
    {
        id: "9",
        title: "Drifting Home",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/iNf1wC8cK6e8zgNyuMUqWFT7Din.jpg",
        decription: "Paranormal investigators Ed and Lorraine Warren work ",
        rate: 2,
        type: "Comedies",
    },
    {
        id: "10",
        title: "SPY x FAMILY",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/3r4LYFuXrg3G8fepysr4xSLWnQL.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
        type: "Action",
    },
    {
        id: "11",
        title: "Peaky Blinders",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 1,
        type: "Comedies",
    },
    {
        id: "12",
        title: "Transporter 3",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/gucv9gRRnVFDyqeIS1KC7irnX0b.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
        type: "Action",
    },
    {
        id: "13",
        title: "Pokémon",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/rOuGm07PxBhEsK9TaGPRQVJQm1X.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
        type: "Action",
    },
    {
        id: "14",
        title: "The School for Good and Evil",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/6oZeEu1GDILdwezmZ5e2xWISf1C.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
        type: "Romance",
    },
    {
        id: "15",
        title: "The Forbidden Kingdom",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/mkrwLBAFHwLnQF8qdhCH0VOQqff.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 2,
        type: "Action",
    },
    {
        id: "16",
        title: "The Three Musketeers",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/w2LbQ8FvZiQpWvZyHljaOeiNknK.jpg",
        decription: "Sensitively written and beautifully acted,",
        rate: 4,
        type: "Romance",
    },
    {
        id: "17",
        title: "TO LESLIE",
        poster: "https://resizing.flixster.com/sMutkU7QCfmhL8tA3ffM_2thwfg=/fit-in/180x240/v2/https://resizing.flixster.com/dQemf-_p3Z3VSLluHicFzfQqCjE=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2Q2MGQ1ZjYzLTA2ODQtNDdiYi1hOThkLTU3ZDY4N2FhYzdjMy5qcGc=",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 5,
        type: "Action",
    },
    {
        id: "18",
        title: "GIRL PICTURE",
        poster: "https://resizing.flixster.com/I9mVWSLEcHgkIgsgQ5OcqZxojfU=/fit-in/180x240/v2/https://resizing.flixster.com/iAoLGlEDhLpEnuQgU9mmvV87oxI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2Q1NWFmYzNiLWE4NjAtNDgwNy1hMjY4LWE3MmQ3YmNhN2IyYS5qcGc=",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 1,
        type: "Romance",
    },
    {
        id: "19",
        title: "COME FROM AWAY",
        poster: "https://resizing.flixster.com/XieLEwzKZpNuld6MPGtgMdfHGvs=/fit-in/180x240/v2/https://resizing.flixster.com/iW2TIykdfWXa_uBdl6lYe-su4eE=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzUwMjYzMWNhLWM3YTgtNGZjYy1iNWM0LWFkZGYyODJhYzMzOC5wbmc=",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
        type: "Action",
    },
    {
        id: "20",
        title: "HELLBENDER",
        poster: "https://resizing.flixster.com/euuOS2dpsjVhtepiSpH7JmPNGXw=/fit-in/180x240/v2/https://resizing.flixster.com/2bMuBHf5qODGQe36bec8YuImCMc=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2ViMzcwOWM4LTU3NGQtNDkyOS05ZGFlLWM5YWU2ZjhmMTIyMy5qcGc=",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 4,
        type: "Comedies",
    },
];

export default ourFilms;